# permissions for end users to view cloudflaretunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflaretunnel-viewer-role
rules:
- apiGroups:
  - cloudflare-tunnel-operator.beezlabs.app
  resources:
  - cloudflaretunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudflare-tunnel-operator.beezlabs.app
  resources:
  - cloudflaretunnels/status
  verbs:
  - get
