---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloudflare-tunnel-operator.beezlabs.app
  resources:
  - cloudflaretunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare-tunnel-operator.beezlabs.app
  resources:
  - cloudflaretunnels/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare-tunnel-operator.beezlabs.app
  resources:
  - cloudflaretunnels/status
  verbs:
  - get
  - patch
  - update
