apiVersion: cloudflare-tunnel-operator.beezlabs.app/v1alpha1
kind: CloudflareTunnel
metadata:
  name: sample-tunnel
spec:
  domain: test.example.com
  zone: example.com
  service:
    name: traefik
    namespace: traefik
    protocol: https
    port: 443
  tokenSecretName: sample-tunnel
  replicas: 1
