apiVersion: cloudflare-tunnel-operator.beezlabs.app/v1alpha1
kind: CloudflareTunnel
metadata:
  name: cloudflaretunnel-sample
spec:
  url: test.example.com
  tunnel: testtunnel
  credentialSecretName: cloudflaretunnel-sample
  replicas: 1
